### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by lokenx** [lokenx/plexrequests-python#2]
Determine the best route to go about creating user accounts. We want users to use their Plex.tv accounts however Plex doesn't have OAuth or social login (think Facebook/Twitter/Google/etc).

We could make users register new accounts and check their username against the shared users of the Plex Media Server. However, that isn't the greatest user experience but a possibility.

The current way of doing things is to only have a login form. When a user logs in they get checked like a regular user would, however instead of failing at that point we do a few more checks. We check their username against the shared users of the Plex Media Server, and if the username exists and they authenticate against Plex.tv we then create an account for them. They're now in the system and good to go.

I haven't thought of a better way to go about this from a user experience end point, it just requires a lot of custom login logic which is fragile.

**Comment by Kryptonit3-zz** [comment]
Here is what I am doing and it works beautifully. The first user, server owner, logs in to their Plex.tv account, I grab their plex_token so I can perform actions with their account later (check friends list etc). Every user that logs in with their plex.tv account after that, i create a local database record for them. Here is my `users` database schema

https://github.com/Kryptonit3/plexrequests-php/blob/master/database/migrations/2014_10_12_000000_create_users_table.php

No need for a password column because they will always authenticate with plex.tv account. I persist their login with a cookie so they don't have to login much. Grab their email incase I decide to implement notifications later etc.

I only allow users to login if they meet the following criteria:
- Must be friends with admin (plex server owner - because if they aren't they can't watch plex server content anyways)
- Must not be in plex user block list in admin settings.

Here is an example of that
https://github.com/Kryptonit3/plexrequests-php/blob/master/app/Http/Controllers/AccountController.php#L21-L93

You will notice that I "CreateOrUpdate" so that if a users plex token or email ever changes, the database will reflect it.

**Comment by Kryptonit3-zz** [comment]
Here is code for the initial user account creation (server owner)

https://github.com/Kryptonit3/plexrequests-php/blob/master/app/Http/Controllers/AdminController.php#L74-L113

**Comment by lokenx** [comment]
Hmm interesting way to do it. I think I'd prefer to make local accounts in Django but I'll have to play around and see. I want to use JWT for authentication as I'll also be exposing an API for front-ends/other apps so not sure how that would work without a password in the database to generate it with.

**Comment by lokenx** [comment]
Implement as of a284da4959dc7f99eb3a708a37885216e7f93104
